
// This file has been generated by the GUI designer. Do not modify.
namespace Cygni.PokerClient
{
	public partial class StatusWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Statusbar topStatus;
		
		private global::Gtk.Label topLabelLeft;
		
		private global::Gtk.Label topLabelRight;
		
		private global::Gtk.DrawingArea drawingArea;
		
		private global::Gtk.Statusbar bottomStatus;
		
		private global::Gtk.Label bottomLabelLeft;
		
		private global::Gtk.Label bottomLabelRight;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cygni.PokerClient.StatusWindow
			this.Name = "Cygni.PokerClient.StatusWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("StatusWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Cygni.PokerClient.StatusWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.topStatus = new global::Gtk.Statusbar ();
			this.topStatus.Name = "topStatus";
			this.topStatus.Spacing = 6;
			// Container child topStatus.Gtk.Box+BoxChild
			this.topLabelLeft = new global::Gtk.Label ();
			this.topLabelLeft.Name = "topLabelLeft";
			this.topStatus.Add (this.topLabelLeft);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.topStatus [this.topLabelLeft]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			// Container child topStatus.Gtk.Box+BoxChild
			this.topLabelRight = new global::Gtk.Label ();
			this.topLabelRight.Name = "topLabelRight";
			this.topStatus.Add (this.topLabelRight);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.topStatus [this.topLabelRight]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.topStatus);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.topStatus]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.drawingArea = new global::Gtk.DrawingArea ();
			this.drawingArea.Name = "drawingArea";
			this.vbox2.Add (this.drawingArea);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.drawingArea]));
			w4.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.bottomStatus = new global::Gtk.Statusbar ();
			this.bottomStatus.Name = "bottomStatus";
			this.bottomStatus.Spacing = 6;
			// Container child bottomStatus.Gtk.Box+BoxChild
			this.bottomLabelLeft = new global::Gtk.Label ();
			this.bottomLabelLeft.Name = "bottomLabelLeft";
			this.bottomStatus.Add (this.bottomLabelLeft);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.bottomStatus [this.bottomLabelLeft]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child bottomStatus.Gtk.Box+BoxChild
			this.bottomLabelRight = new global::Gtk.Label ();
			this.bottomLabelRight.Name = "bottomLabelRight";
			this.bottomStatus.Add (this.bottomLabelRight);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.bottomStatus [this.bottomLabelRight]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add (this.bottomStatus);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.bottomStatus]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 823;
			this.DefaultHeight = 579;
			this.Show ();
		}
	}
}
